### ISSUE TITLE
Compatibility Issue: Extension not functional on Chromium

### ISSUE THREAD

**Issue by Arkalo2** [combatwombat/netbeep#1]
Hello, it does not work on my browser. I use chromium Version 112.0.5615.49 on Ubuntu 20.04

**Comment by combatwombat** [comment]
Thanks for the feedback. What computer do you have, specs-wise? Slower ones seem to get overwhelmed earlier with too many notes. Maybe the speed of notes playing needs to be configurable..

**Comment by Arkalo2** [comment]
I have a good configuration on my  good configuration
 
CPU : 11th Gen Intel® Core™ i5-1145G7 @ 2.60GHz × 8 
GPU : Mesa Intel® Xe Graphics (TGL GT2)
RAM : 32G

And it's laptop

**Comment by combatwombat** [comment]
That should be plenty. It also works here on macOS with Chromium and Thorium. if you want to debug a bit:

Does the Firefox extension work on your system?
And does this play any sound? https://robertgerlach.net/tmp/tonejs-test.html

**Comment by combatwombat** [comment]
Great. Still weird that Chromium doesn't work, but at least it's not something fundamentally wrong. Thanks for testing.
