### ISSUE TITLE
[feature request] add to firefox? 

### ISSUE THREAD

**Issue by Lunardog15** [combatwombat/netbeep#2]
a version that works with firefox would be nice!

**Comment by combatwombat** [comment]
It’s planned, but might take a while.

**Comment by Lunardog15** [comment]
yay!

**Comment by combatwombat** [comment]
It should work in Firefox now. It's not in the Add-on store yet, but if you want to try it before that, load it via *Debug Add-ons* > *Load Temporary Add-on...* and select `dist/firefox/src/manifest.json`

**Comment by combatwombat** [comment]
Alright, it's online :) https://addons.mozilla.org/de/firefox/addon/netbeep/
